name: Extract img file

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      type_file:
        description: "Select type file"
        required: false
        default: "img.gz"
        type: choice
        options:
          - img.xz
          - img.gz
      img_url:
        description: "Set the url img file"
        required: true
        default: ""
      rename_rootfs:
        description: "Rename rootfs"
        required: true
        default: ""

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize environment
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get -qq update
        sudo apt-get install -y wget python3 python3-pip
        sudo apt-get autoremove -y --purge
        sudo apt-get clean
        pip3 install --upgrade gdown
        pip3 install --upgrade git+https://github.com/Juvenal-Yescas/mediafire-dl
        wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb
        sudo apt install -y "$PWD/megacmd-xUbuntu_22.04_amd64.deb"
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir/openwrt
        sudo chown $USER:$GROUPS /workdir

    - name: Download file ${{ github.event.inputs.type_file }}
      working-directory: /workdir
      run: |
        df -hT $PWD
        FILE=openwrt/file.${{ github.event.inputs.type_file }}
        URL="${{ github.event.inputs.img_url }}"
        if [[ "$URL" =~ "drive." ]]; then
          FILE_ID=$(echo "$URL" | awk -F "/" '{print $6}')
          [[ -z "$FILE_ID" ]] && FILE_ID=$(echo "$URL" | awk -F "id=" '{print $2}' | awk -F "&" '{print $1}')
          gdown "$FILE_ID" -O "$FILE"
        elif [[ "$URL" =~ "mediafire.com" ]]; then
          mediafire-dl "$URL" -o "$FILE"
        elif [[ "$URL" =~ "mega.nz" ]]; then
          TMP=$(mega-get "$URL" | awk -F: '{print $2}')
          mv "$TMP" "$FILE"
        else
          wget --no-check-certificate "$URL" -O "$FILE"
        fi
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Extract firmware
      id: extract
      run: |
        cd openwrt
        mkdir -p boot rootfs img
        if [[ "${{ github.event.inputs.type_file }}" == "img.gz" ]]; then
          gunzip -c file.img.gz > file.img
        else
          xz -d -c file.img.xz > file.img
        fi
        los=$(sudo losetup -fP --show file.img)
        sudo mount ${los}p2 rootfs
        (cd rootfs && sudo tar czf /workdir/openwrt/img/${{ github.event.inputs.rename_rootfs }}.tar.gz *)
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Check space usage
      run: df -hT

    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: openwrt/img/*
        file_glob: true
        overwrite: true
        tag: ${{ github.ref }}
        body: |
          ##  KUMPULAN HASIL MALINK ROOTFS

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        
